steps:
 - id: decrypt-key
   name: gcr.io/cloud-builders/gcloud
   args:
   - kms
   - decrypt
   - --ciphertext-file=functions/credentials.json.enc
   - --plaintext-file=functions/credentials.json
   - --location=global
   - --keyring=luuk180-dev
   - --key=githubFunction
 - id: install_packages
   name: 'node'
   entrypoint: 'npm'
   args: ['install']
 - id: install_functions_packages
   name: 'node'
   entrypoint: 'npm'
   args: ['install']
   dir: functions
 - id: build_deploy
   name: 'node'
   entrypoint: 'npm'
   args: ['run', 'deploy']
   waitFor:
   - install_packages
   - install_functions_packages
   - decrypt-key
