steps:
 - id: install_packages
   name: 'node'
   entrypoint: 'npm'
   args: ['install']
 - id: install_functions_packages
   name: 'node'
   entrypoint: 'npm'
   args: ['install']
   dir: functions
 - id: build_deploy
   name: 'node'
   entrypoint: 'npm'
   args: ['run', 'deploy']
   waitFor:
   - install_packages
   - install_functions_packages
